### PR TITLE
asynchronous

### PR DESCRIPTION
**Pull request by itIsMaku**

### CODE REVIEW

**Comment by itIsMaku** [comment]
@Gennario Please response to my PR.

**Comment by Gennario** [comment]
@itIsMaku there's some conflicts.. Please resolve them 
obrazek

**Comment by itIsMaku** [comment]
Of course that conflicts are there. What do you expected if you reworked complete code? 😄 This pull request is 2 months old lol.

**Comment by itIsMaku** [comment]
Closing pull request because author rewrited entire code.

**Pull request closed without merging**
